export const grove = {
  id00: {
    id: "id00",
    name: "Spring of Life",
    prev: null,
    next: null,
    pos: [0, 0],
    cost: { gold: 0 },
    produces: {},
  },
  id10: {
    id: "id10",
    name: "Tavern",
    prev: null,
    next: ["id20"],
    pos: [1, 0],
    cost: { gold: 500, ore: 5 },
    produces: {},
  },
  id20: {
    id: "id20",
    name: "Marketplace",
    prev: ["id10"],
    next: ["id31", "id30"],
    pos: [2, 0],
    cost: { gold: 500, wood: 5 },
    produces: {},
  },
  id30: {
    id: "id30",
    name: "Artifact Merchant",
    prev: ["id20"],
    next: null,
    pos: [3, 0],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: {},
  },
  id01: {
    id: "id01",
    name: "Grove Place",
    prev: null,
    next: ["id11"],
    pos: [0, 1],
    cost: { gold: 0 },
    produces: { gold: 500, law: 500, astrology: 500 },
  },
  id11: {
    id: "id11",
    name: "Grove Place II",
    prev: ["id01"],
    next: ["id21", "id22"],
    pos: [1, 1],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: { gold: 250, law: 250, astrology: 250 },
  },
  id21: {
    id: "id21",
    name: "Grove Place III",
    prev: ["id11"],
    next: null,
    pos: [2, 1],
    cost: { gold: 5000, wood: 10, ore: 10 },
    produces: { gold: 250, law: 250, astrology: 250 },
  },
  id31: {
    id: "id31",
    name: "Resource Depot",
    prev: ["id20", "id22"],
    next: ["id41"],
    pos: [3, 1],
    cost: { gold: 2000 },
    produces: { crystals: 1 },
  },
  id41: {
    id: "id41",
    name: "Alchemic Depot",
    prev: ["id31"],
    next: null,
    pos: [4, 1],
    cost: { gems: 3, crystals: 3, mercury: 3 },
    produces: { dust: 5 },
  },
  id02: {
    id: "id02",
    name: "Mother Nature",
    prev: null,
    next: null,
    pos: [0, 2],
    cost: { gold: 5000 },
    produces: {},
  },
  id22: {
    id: "id22",
    name: "Bank",
    prev: ["id11"],
    next: ["id31", "id32"],
    pos: [2, 2],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: { gold: 1000 },
  },
  id32: {
    id: "id32",
    name: "Treasury",
    prev: ["id22", "id23"],
    next: null,
    pos: [3, 2],
    cost: { gold: 5000, gems: 5, crystals: 5, mercury: 5 },
    produces: { gold: 2000 },
  },
  id42: {
    id: "id42",
    name: "Mycelium Roots",
    prev: ["id33"],
    next: null,
    pos: [4, 2],
    cost: { gold: 5000, gems: 5, crystals: 5, mercury: 5 },
    produces: {},
  },
  id23: {
    id: "id23",
    name: "Fortifications",
    prev: null,
    next: ["id33"],
    pos: [2, 3],
    cost: { gold: 2500, ore: 5 },
    produces: {},
  },
  id33: {
    id: "id33",
    name: "Fortifications II",
    prev: ["id23"],
    next: ["id43", "id42"],
    pos: [3, 3],
    cost: { gold: 2500, ore: 10 },
    produces: {},
  },
  id43: {
    id: "id43",
    name: "Fortifications III",
    prev: ["id33"],
    next: null,
    pos: [4, 3],
    cost: { gold: 5000, ore: 15 },
    produces: {},
  },
  id14: {
    id: "id14",
    name: "Faun Huts II",
    prev: ["id05"],
    next: null,
    pos: [1, 4],
    cost: { gold: 750, wood: 5, dust: 10 },
    produces: {},
  },
  id24: {
    id: "id24",
    name: "Hop Patch II",
    prev: ["id15"],
    next: null,
    pos: [2, 4],
    cost: { gold: 1250, crystals: 5, dust: 20 },
    produces: {},
  },
  id05: {
    id: "id05",
    name: "Faun Huts",
    prev: null,
    next: ["id14"],
    pos: [0, 5],
    cost: { gold: 0 },
    produces: {},
  },
  id15: {
    id: "id15",
    name: "Hop Patch",
    prev: ["id05"],
    next: ["id24", "id25", "id26"],
    pos: [1, 5],
    cost: { gold: 1000, gems: 2, crystals: 2, mercury: 2 },
    produces: {},
  },
  id25: {
    id: "id25",
    name: "Shroomwood Shack",
    prev: ["id15"],
    next: ["id35"],
    pos: [2, 5],
    cost: { gold: 2750, wood: 10, gems: 4, crystals: 4, mercury: 4 },
    produces: {},
  },
  id35: {
    id: "id35",
    name: "Shroomwood Shack II",
    prev: ["id25"],
    next: null,
    pos: [3, 5],
    cost: { gold: 3250, wood: 20, crystals: 4, dust: 50 },
    produces: {},
  },
  id06: {
    id: "id06",
    name: "Menhir Circle",
    prev: null,
    next: ["id16", "id17"],
    pos: [0, 6],
    cost: { gold: 2000, wood: 5, ore: 5, crystals: 3 },
    produces: {},
  },
  id16: {
    id: "id16",
    name: "Menhir Circle II",
    prev: ["id06"],
    next: null,
    pos: [1, 6],
    cost: { gold: 1000, wood: 5, ore: 5, crystals: 3, dust: 30 },
    produces: {},
  },
  id26: {
    id: "id26",
    name: "Thunder Lair",
    prev: ["id15", "id17"],
    next: ["id36", "id37"],
    pos: [2, 6],
    cost: { gold: 6500, wood: 5, ore: 5, crystals: 5 },
    produces: {},
  },
  id36: {
    id: "id36",
    name: "Thunder Lair II",
    prev: ["id26"],
    next: null,
    pos: [3, 6],
    cost: { gold: 3500, wood: 10, ore: 10, crystals: 10, dust: 75 },
    produces: {},
  },
  id17: {
    id: "id17",
    name: "Booming Pond",
    prev: ["id06", "id08"],
    next: ["id27", "id26"],
    pos: [1, 7],
    cost: { gold: 2500, ore: 5, crystals: 5 },
    produces: {},
  },
  id27: {
    id: "id27",
    name: "Booming Pond II",
    prev: ["id17"],
    next: null,
    pos: [2, 7],
    cost: { gold: 1500, ore: 5, crystals: 5, dust: 40 },
    produces: {},
  },
  id37: {
    id: "id37",
    name: "Pyre",
    prev: ["id26"],
    next: ["id47"],
    pos: [3, 7],
    cost: { gold: 12500, wood: 5, ore: 5, crystals: 20 },
    produces: {},
  },
  id47: {
    id: "id47",
    name: "Pyre II",
    prev: ["id37"],
    next: null,
    pos: [4, 7],
    cost: { gold: 20000, wood: 5, ore: 5, crystals: 20, dust: 100 },
    produces: {},
  },
  id08: {
    id: "id08",
    name: "Mage Guild",
    prev: null,
    next: ["id18"],
    pos: [0, 8],
    cost: { gold: 2500, wood: 5 },
    produces: {},
  },
  id18: {
    id: "id18",
    name: "Mage Guild II",
    prev: ["id08"],
    next: ["id28"],
    pos: [1, 8],
    cost: { gold: 2500, gems: 2, crystals: 2, mercury: 2 },
    produces: {},
  },
  id28: {
    id: "id28",
    name: "Mage Guild III",
    prev: ["id18"],
    next: ["id38"],
    pos: [2, 8],
    cost: { gold: 2500, wood: 5, gems: 3, crystals: 3, mercury: 3 },
    produces: {},
  },
  id38: {
    id: "id38",
    name: "Mage Guild IV",
    prev: ["id28"],
    next: ["id48"],
    pos: [3, 8],
    cost: { gold: 2500, gems: 5, crystals: 5, mercury: 5 },
    produces: {},
  },
  id48: {
    id: "id48",
    name: "Mage Guild V",
    prev: ["id38"],
    next: null,
    pos: [4, 8],
    cost: { gold: 5000, wood: 10, gems: 5, crystals: 5, mercury: 5 },
    produces: {},
  },
} as const;
