export const grove = {
  id00: {
    id: "id00",
    name: "Spring of Life",
    prev: null,
    next: null,
    pos: [0, 0],
    cost: { gold: 0 },
    produces: {},
    description: "+1 to all creature growth in all your cities. This city’s dwellings produce +100% units.",
  },
  id10: {
    id: "id10",
    name: "Tavern",
    prev: null,
    next: ["id20"],
    pos: [1, 0],
    cost: { gold: 500, ore: 5 },
    produces: {},
    description: "Allows the hiring of new heroes.",
  },
  id20: {
    id: "id20",
    name: "Marketplace",
    prev: ["id10"],
    next: ["id31", "id30"],
    pos: [2, 0],
    cost: { gold: 500, wood: 5 },
    produces: {},
    description: "Allows resources to be traded.",
  },
  id30: {
    id: "id30",
    name: "Artifact Merchant",
    prev: ["id20"],
    next: null,
    pos: [3, 0],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: {},
    description: "Allows artifacts to be traded.",
  },
  id01: {
    id: "id01",
    name: "Grove Place",
    prev: null,
    next: ["id11"],
    pos: [0, 1],
    cost: { gold: 0 },
    produces: { gold: 500, law: 500, astrology: 500 },
    description: "Grants the kingdom 500 Gold, Law points, and Astrology points daily. +1 hero cap.",
  },
  id11: {
    id: "id11",
    name: "Grove Place II",
    prev: ["id01"],
    next: ["id21", "id22"],
    pos: [1, 1],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: { gold: 250, law: 250, astrology: 250 },
    description: "Grants the kingdom 750 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-1 economy upgrade.",
  },
  id21: {
    id: "id21",
    name: "Grove Place III",
    prev: ["id11"],
    next: null,
    pos: [2, 1],
    cost: { gold: 5000, wood: 10, ore: 10 },
    produces: { gold: 250, law: 250, astrology: 250 },
    description: "Grants the kingdom 1000 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-2 economy upgrade.",
  },
  id31: {
    id: "id31",
    name: "Resource Depot",
    prev: ["id20", "id22"],
    next: ["id41"],
    pos: [3, 1],
    cost: { gold: 2000 },
    produces: { crystals: 1 },
    description: "Produces 1 Crystal daily.",
  },
  id41: {
    id: "id41",
    name: "Alchemic Depot",
    prev: ["id31"],
    next: null,
    pos: [4, 1],
    cost: { gems: 3, crystals: 3, mercury: 3 },
    produces: { dust: 5 },
    description: "Produces 5 Alchemical Dust daily.",
  },
  id02: {
    id: "id02",
    name: "Mother Nature",
    prev: null,
    next: null,
    pos: [0, 2],
    cost: { gold: 5000 },
    produces: {},
    description: "Grants +2 Spell Power to any visiting hero.",
  },
  id22: {
    id: "id22",
    name: "Bank",
    prev: ["id11"],
    next: ["id31", "id32"],
    pos: [2, 2],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: { gold: 1000 },
    description: "Produces 1000 Gold daily.",
  },
  id32: {
    id: "id32",
    name: "Treasury",
    prev: ["id22", "id23"],
    next: null,
    pos: [3, 2],
    cost: { gold: 5000, gems: 5, crystals: 5, mercury: 5 },
    produces: { gold: 2000 },
    description: "Produces 2000 Gold daily.",
  },
  id42: {
    id: "id42",
    name: "Mycelium Roots",
    prev: ["id33"],
    next: null,
    pos: [4, 2],
    cost: { gold: 5000, gems: 5, crystals: 5, mercury: 5 },
    produces: {},
    description: "Allows a hero to travel to any city of their choice under your control.",
  },
  id23: {
    id: "id23",
    name: "Fortifications",
    prev: null,
    next: ["id33"],
    pos: [2, 3],
    cost: { gold: 2500, ore: 5 },
    produces: {},
    description: "Provides walls during sieges. Allows the builder to pick one level-1 defensive upgrade.",
  },
  id33: {
    id: "id33",
    name: "Fortifications II",
    prev: ["id23"],
    next: ["id43", "id42"],
    pos: [3, 3],
    cost: { gold: 2500, ore: 10 },
    produces: {},
    description: "Adds two towers to the battlements that shoot at attackers during sieges. Allows the builder to pick one level-2 defensive upgrade. City dwellings produce +50% units.",
  },
  id43: {
    id: "id43",
    name: "Fortifications III",
    prev: ["id33"],
    next: null,
    pos: [4, 3],
    cost: { gold: 5000, ore: 15 },
    produces: {},
    description: "Adds one more grand tower to the battlements that shoots at attackers during sieges and spikes by the walls. Allows the builder to pick one level-3 defensive upgrade. City dwellings produce +100% units.",
  },
  id14: {
    id: "id14",
    name: "Faun Huts II",
    prev: ["id05"],
    next: null,
    pos: [1, 4],
    cost: { gold: 750, wood: 5, dust: 10 },
    produces: {},
    description: "Allows the recruitment of Faun Archers and Faun Warriors.",
  },
  id24: {
    id: "id24",
    name: "Hop Patch II",
    prev: ["id15"],
    next: null,
    pos: [2, 4],
    cost: { gold: 1500, crystals: 2, dust: 20 },
    produces: {},
    description: "Allows the recruitment of Dawn Hoplets and Dusk Hoplets.",
  },
  id05: {
    id: "id05",
    name: "Faun Huts",
    prev: null,
    next: ["id14"],
    pos: [0, 5],
    cost: { gold: 0 },
    produces: {},
    description: "Allows the recruitment of Fauns.",
  },
  id15: {
    id: "id15",
    name: "Hop Patch",
    prev: ["id05"],
    next: ["id24", "id25", "id26"],
    pos: [1, 5],
    cost: { gold: 1250, gems: 2, crystals: 2, mercury: 2 },
    produces: {},
    description: "Allows the recruitment of Hoplets.",
  },
  id25: {
    id: "id25",
    name: "Shroomwood Shack",
    prev: ["id15"],
    next: ["id35"],
    pos: [2, 5],
    cost: { gold: 2250, wood: 10, gems: 4, crystals: 4, mercury: 4 },
    produces: {},
    description: "Allows the recruitment of Herbomancers.",
  },
  id35: {
    id: "id35",
    name: "Shroomwood Shack II",
    prev: ["id25"],
    next: null,
    pos: [3, 5],
    cost: { gold: 3250, wood: 15, crystals: 4, dust: 50 },
    produces: {},
    description: "Allows the recruitment of Sporemancers and Murmurmancers",
  },
  id06: {
    id: "id06",
    name: "Menhir Circle",
    prev: null,
    next: ["id16", "id17"],
    pos: [0, 6],
    cost: { gold: 2000, wood: 5, ore: 5, crystals: 3 },
    produces: {},
    description: "Allows the recruitment of Vine Iriyads.",
  },
  id16: {
    id: "id16",
    name: "Menhir Circle II",
    prev: ["id06"],
    next: null,
    pos: [1, 6],
    cost: { gold: 1000, wood: 5, ore: 5, crystals: 3, dust: 30 },
    produces: {},
    description: "Allows the recruitment of Fungal Iriyads and Crystal Iriyads.",
  },
  id26: {
    id: "id26",
    name: "Thunder Lair",
    prev: ["id15", "id17"],
    next: ["id36", "id37"],
    pos: [2, 6],
    cost: { gold: 6000, wood: 5, ore: 5, crystals: 5 },
    produces: {},
    description: "Allows the recruitment of Qilins.",
  },
  id36: {
    id: "id36",
    name: "Thunder Lair II",
    prev: ["id26"],
    next: null,
    pos: [3, 6],
    cost: { gold: 3000, wood: 10, ore: 10, crystals: 10, dust: 75 },
    produces: {},
    description: "Allows the recruitment of Thunder Qilins and Mist Qilins.",
  },
  id17: {
    id: "id17",
    name: "Blooming Pond",
    prev: ["id06", "id08"],
    next: ["id27", "id26"],
    pos: [1, 7],
    cost: { gold: 2750, ore: 5, crystals: 5 },
    produces: {},
    description: "Allows the recruitment of Naiads.",
  },
  id27: {
    id: "id27",
    name: "Blooming Pond II",
    prev: ["id17"],
    next: null,
    pos: [2, 7],
    cost: { gold: 1750, ore: 5, crystals: 5, dust: 40 },
    produces: {},
    description: "Allows the recruitment of Vernal Naiads and Brumal Naiads.",
  },
  id37: {
    id: "id37",
    name: "Pyre",
    prev: ["id26"],
    next: ["id47"],
    pos: [3, 7],
    cost: { gold: 12500, wood: 5, ore: 5, crystals: 20 },
    produces: {},
    description: "Allows the recruitment of Phoenixes.",
  },
  id47: {
    id: "id47",
    name: "Pyre II",
    prev: ["id37"],
    next: null,
    pos: [4, 7],
    cost: { gold: 20000, wood: 5, ore: 5, crystals: 20, dust: 100 },
    produces: {},
    description: "Allows the recruitment of Flaming Phoenixes and Energy Phoenixes.",
  },
  id08: {
    id: "id08",
    name: "Mage Guild",
    prev: null,
    next: ["id18"],
    pos: [0, 8],
    cost: { gold: 2500, wood: 5 },
    produces: {},
    description: "Unlocks 7 random tier‑1 spells in the Magic Observatory and the ability to spend dust to upgrade tier-1 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1 spells are added to their Spellbook.",
  },
  id18: {
    id: "id18",
    name: "Mage Guild II",
    prev: ["id08"],
    next: ["id28"],
    pos: [1, 8],
    cost: { gold: 2500, gems: 2, crystals: 2, mercury: 2 },
    produces: {},
    description: "Unlocks 6 random tier‑2 spells in the Magic Observatory and the ability to spend dust to upgrade tier-2 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–2 spells are added to their Spellbook.",
  },
  id28: {
    id: "id28",
    name: "Mage Guild III",
    prev: ["id18"],
    next: ["id38"],
    pos: [2, 8],
    cost: { gold: 2500, wood: 5, gems: 3, crystals: 3, mercury: 3 },
    produces: {},
    description: "Unlocks 5 random tier‑3 spells in the Magic Observatory and the ability to spend dust to upgrade tier-3 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–3 spells are added to their Spellbook.",
  },
  id38: {
    id: "id38",
    name: "Mage Guild IV",
    prev: ["id28"],
    next: ["id48"],
    pos: [3, 8],
    cost: { gold: 2500, gems: 5, crystals: 5, mercury: 5 },
    produces: {},
    description: "Unlocks 4 random tier‑4 spells in the Magic Observatory and the ability to spend dust to upgrade tier-4 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–4 spells are added to their Spellbook.",
  },
  id48: {
    id: "id48",
    name: "Mage Guild V",
    prev: ["id38"],
    next: null,
    pos: [4, 8],
    cost: { gold: 5000, wood: 10, gems: 5, crystals: 5, mercury: 5 },
    produces: {},
    description: "Unlocks 3 random tier‑5 spells in the Magic Observatory and the ability to spend dust to upgrade tier-5 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–5 spells are added to their Spellbook.",
  },
} as const;
