export const necropolis = {
  id00: {
    id: "id00",
    name: "Everserpent",
    prev: null,
    next: null,
    pos: [0, 0],
    cost: { gold: 0 },
    produces: {},
    description: "All friendly creatures gain +10 Defense and take –50% Lucky Strike Damage in battle (including from spells). This city’s dwellings produce +100% units.",
  },
  id10: {
    id: "id10",
    name: "Tavern",
    prev: null,
    next: ["id20"],
    pos: [1, 0],
    cost: { gold: 500, ore: 5 },
    produces: {},
    description: "Allows the hiring of new heroes.",
  },
  id20: {
    id: "id20",
    name: "Marketplace",
    prev: ["id10"],
    next: ["id31"],
    pos: [2, 0],
    cost: { gold: 500, wood: 5 },
    produces: {},
    description: "Allows resources to be traded.",
  },
  id01: {
    id: "id01",
    name: "Eternal Visage",
    prev: null,
    next: ["id11"],
    pos: [0, 1],
    cost: { gold: 0 },
    produces: { gold: 500, law: 500, astrology: 500 },
    description: "Grants the kingdom 500 Gold, Law points, and Astrology points daily. +1 hero cap.",
  },
  id11: {
    id: "id11",
    name: "Eternal Visage II",
    prev: ["id01"],
    next: ["id21", "id22"],
    pos: [1, 1],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: { gold: 250, law: 250, astrology: 250 },
    description: "Grants the kingdom 750 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-1 economy upgrade.",
  },
  id21: {
    id: "id21",
    name: "Eternal Visage III",
    prev: ["id11"],
    next: null,
    pos: [2, 1],
    cost: { gold: 5000, wood: 10, ore: 10 },
    produces: { gold: 250, law: 250, astrology: 250 },
    description: "Grants the kingdom 1000 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-2 economy upgrade.",
  },
  id31: {
    id: "id31",
    name: "Resource Depot",
    prev: ["id20", "id22"],
    next: ["id41"],
    pos: [3, 1],
    cost: { gold: 2000 },
    produces: { mercury: 1 },
    description: "Produces 1 Mercury daily.",
  },
  id41: {
    id: "id41",
    name: "Alchemic Depot",
    prev: ["id31"],
    next: null,
    pos: [4, 1],
    cost: { gems: 3, crystals: 3, mercury: 3 },
    produces: { dust: 5 },
    description: "Produces 5 Alchemical Dust daily.",
  },
  id22: {
    id: "id22",
    name: "Bank",
    prev: ["id11"],
    next: ["id31", "id32"],
    pos: [2, 2],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: { gold: 1000 },
    description: "Produces 1000 Gold daily.",
  },
  id32: {
    id: "id32",
    name: "Treasury",
    prev: ["id22", "id23"],
    next: null,
    pos: [3, 2],
    cost: { gold: 5000, gems: 5, crystals: 5, mercury: 5 },
    produces: { gold: 2000 },
    description: "Produces 2000 Gold daily.",
  },
  id23: {
    id: "id23",
    name: "Fortifications",
    prev: null,
    next: ["id33"],
    pos: [2, 3],
    cost: { gold: 2500, ore: 5 },
    produces: {},
    description: "Provides walls during sieges. Allows the builder to pick one level-1 defensive upgrade.",
  },
  id33: {
    id: "id33",
    name: "Fortifications II",
    prev: ["id23"],
    next: ["id43"],
    pos: [3, 3],
    cost: { gold: 2500, ore: 10 },
    produces: {},
    description: "Adds two towers to the battlements that shoot at attackers during sieges. Allows the builder to pick one level-2 defensive upgrade. City dwellings produce +50% units.",
  },
  id43: {
    id: "id43",
    name: "Fortifications III",
    prev: ["id33"],
    next: null,
    pos: [4, 3],
    cost: { gold: 5000, ore: 15 },
    produces: {},
    description: "Adds one more grand tower to the battlements that shoots at attackers during sieges and spikes by the walls. Allows the builder to pick one level-3 defensive upgrade. City dwellings produce +100% units.",
  },
  id04: {
    id: "id04",
    name: "Undead Transformer",
    prev: null,
    next: null,
    pos: [0, 4],
    cost: { gold: 1000, wood: 5, ore: 5 },
    produces: {},
    description: "Allows sacrificing of any creatures to turn them into Undead units of the same tier.",
  },
  id14: {
    id: "id14",
    name: "Kennel",
    prev: ["id05"],
    next: ["id34", "id25"],
    pos: [1, 4],
    cost: { gold: 2750, wood: 10 },
    produces: {},
    description: "Allows the recruitment of Undead Pets.",
  },
  id34: {
    id: "id34",
    name: "Tomb of the Warriors",
    prev: ["id14", "id23"],
    next: ["id44"],
    pos: [3, 4],
    cost: { gold: 7000, wood: 5, ore: 10 },
    produces: {},
    description: "Allows the recruitment of Dread Knights.",
  },
  id44: {
    id: "id44",
    name: "Tomb of the Warriors II",
    prev: ["id34"],
    next: null,
    pos: [4, 4],
    cost: { gold: 5000, ore: 15, mercury: 10, dust: 75 },
    produces: {},
    description: "Allows the recruitment of Avatars of War and Hollow Reapers.",
  },
  id05: {
    id: "id05",
    name: "Crypts and Graves",
    prev: null,
    next: ["id15", "id16", "id14"],
    pos: [0, 5],
    cost: {},
    produces: {},
    description: "Allows the recruitment of Skeletons.",
  },
  id15: {
    id: "id15",
    name: "Crypts and Graves II",
    prev: ["id05"],
    next: null,
    pos: [1, 5],
    cost: { gold: 1000, dust: 10 },
    produces: {},
    description: "Allows the recruitment of Skeleton Warriors and Skeleton Archers.",
  },
  id25: {
    id: "id25",
    name: "Kennel II",
    prev: ["id14"],
    next: null,
    pos: [2, 5],
    cost: { gold: 2500, wood: 5, dust: 30 },
    produces: {},
    description: "Allows the recruitment of Barghests and Armored Hounds.",
  },
  id35: {
    id: "id35",
    name: "Timeless Mansion II",
    prev: ["id26"],
    next: null,
    pos: [3, 5],
    cost: { gold: 2000, mercury: 10, dust: 50 },
    produces: {},
    description: "Allows the recruitment of Pestilent Liches and Sanguine Liches.",
  },
  id16: {
    id: "id16",
    name: "Bone Exchange",
    prev: ["id05", "id07"],
    next: ["id26", "id27"],
    pos: [1, 6],
    cost: { gold: 4500, wood: 5, ore: 5, mercury: 5 },
    produces: {},
    description: "Allows the recruitment of Graverobbers.",
  },
  id26: {
    id: "id26",
    name: "Timeless Mansion",
    prev: ["id16"],
    next: ["id36", "id35"],
    pos: [2, 6],
    cost: { gold: 3500, wood: 5, ore: 5, mercury: 5 },
    produces: {},
    description: "Allows the recruitment of Liches.",
  },
  id36: {
    id: "id36",
    name: "Chateau of Feasts",
    prev: ["id26"],
    next: ["id46"],
    pos: [3, 6],
    cost: { gold: 12500, wood: 15, ore: 15, mercury: 15 },
    produces: {},
    description: "Allows the recruitment of Vampires.",
  },
  id46: {
    id: "id46",
    name: "Chateau of Feasts II",
    prev: ["id36"],
    next: null,
    pos: [4, 6],
    cost: { gold: 17500, wood: 5, ore: 5, mercury: 25, dust: 100 },
    produces: {},
    description: "Allows the recruitment of Vampire Lords and Vampire Scholars.",
  },
  id07: {
    id: "id07",
    name: "Quiet Pavilion",
    prev: null,
    next: ["id17", "id16"],
    pos: [0, 7],
    cost: { gold: 1250, mercury: 5 },
    produces: {},
    description: "Allows the recruitment of Wights.",
  },
  id17: {
    id: "id17",
    name: "Quiet Pavilion II",
    prev: ["id07"],
    next: null,
    pos: [1, 7],
    cost: { gold: 1250, mercury: 5, dust: 20 },
    produces: {},
    description: "Allows the recruitment of Wraiths and Phantasms.",
  },
  id27: {
    id: "id27",
    name: "Bone Exchange II",
    prev: ["id16"],
    next: null,
    pos: [2, 7],
    cost: { gold: 3500, wood: 5, ore: 5, mercury: 5, dust: 40 },
    produces: {},
    description: "Allows the recruitment of Merchants of Death and Kennelmasters.",
  },
  id37: {
    id: "id37",
    name: "Well of Souls",
    prev: ["id28"],
    next: null,
    pos: [3, 7],
    cost: { gold: 2500, mercury: 3, gems: 3, crystals: 3 },
    produces: {},
    description: "Well of Souls",
  },
  id08: {
    id: "id08",
    name: "Mage Guild",
    prev: null,
    next: ["id18"],
    pos: [0, 8],
    cost: { gold: 2500, wood: 5 },
    produces: {},
    description: "Unlocks 7 random tier‑1 spells in the Magic Observatory and the ability to spend dust to upgrade tier-1 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1 spells are added to their Spellbook.",
  },
  id18: {
    id: "id18",
    name: "Mage Guild II",
    prev: ["id08"],
    next: ["id28"],
    pos: [1, 8],
    cost: { gold: 2500, gems: 2, crystals: 2, mercury: 2 },
    produces: {},
    description: "Unlocks 6 random tier‑2 spells in the Magic Observatory and the ability to spend dust to upgrade tier-2 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–2 spells are added to their Spellbook.",
  },
  id28: {
    id: "id28",
    name: "Mage Guild III",
    prev: ["id18"],
    next: ["id38"],
    pos: [2, 8],
    cost: { gold: 2500, wood: 5, gems: 3, crystals: 3, mercury: 3 },
    produces: {},
    description: "Unlocks 5 random tier‑3 spells in the Magic Observatory and the ability to spend dust to upgrade tier-3 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–3 spells are added to their Spellbook.",
  },
  id38: {
    id: "id38",
    name: "Mage Guild IV",
    prev: ["id28"],
    next: ["id48"],
    pos: [3, 8],
    cost: { gold: 2500, gems: 5, crystals: 5, mercury: 5 },
    produces: {},
    description: "Unlocks 4 random tier‑4 spells in the Magic Observatory and the ability to spend dust to upgrade tier-4 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–4 spells are added to their Spellbook.",
  },
  id48: {
    id: "id48",
    name: "Mage Guild V",
    prev: ["id38"],
    next: null,
    pos: [4, 8],
    cost: { gold: 5000, wood: 10, gems: 5, crystals: 5, mercury: 5 },
    produces: {},
    description: "Unlocks 3 random tier‑5 spells in the Magic Observatory and the ability to spend dust to upgrade tier-5 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–5 spells are added to their Spellbook.",
  },
} as const;
