export const schism = {
  id00: {
    id: "id00",
    name: "Firmament's Abyss",
    prev: null,
    next: null,
    pos: [0, 0],
    cost: { gold: 0 },
    produces: {},
  },
  id10: {
    id: "id10",
    name: "Tavern",
    prev: null,
    next: ["id20"],
    pos: [1, 0],
    cost: { gold: 500, ore: 5 },
    produces: {},
  },
  id20: {
    id: "id20",
    name: "Marketplace",
    prev: ["id10"],
    next: ["id31", "id30"],
    pos: [2, 0],
    cost: { gold: 500, wood: 5 },
    produces: {},
  },
  id30: {
    id: "id30",
    name: "Artifact Merchant",
    prev: ["id20"],
    next: null,
    pos: [3, 0],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: {},
  },
  id01: {
    id: "id01",
    name: "Abyssal Remnant",
    prev: null,
    next: ["id11"],
    pos: [0, 1],
    cost: { gold: 0 },
    produces: { gold: 500, law: 500, astrology: 500 },
  },
  id11: {
    id: "id11",
    name: "Abyssal Remnant II",
    prev: ["id01"],
    next: ["id21", "id22"],
    pos: [1, 1],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: { gold: 250, law: 250, astrology: 250 },
  },
  id21: {
    id: "id21",
    name: "Abyssal Remnant III",
    prev: ["id11"],
    next: null,
    pos: [2, 1],
    cost: { gold: 5000, wood: 10, ore: 10 },
    produces: { gold: 250, law: 250, astrology: 250 },
  },
  id31: {
    id: "id31",
    name: "Resource Depot",
    prev: ["id20", "id22"],
    next: ["id41"],
    pos: [3, 1],
    cost: { gold: 2000 },
    produces: { gems: 1 },
  },
  id41: {
    id: "id41",
    name: "Alchemic Depot",
    prev: ["id31"],
    next: null,
    pos: [4, 1],
    cost: { gems: 3, crystals: 3, mercury: 3 },
    produces: { dust: 5 },
  },
  id02: {
    id: "id02",
    name: "Great Library",
    prev: null,
    next: null,
    pos: [0, 2],
    cost: { gold: 5000 },
    produces: {},
  },
  id22: {
    id: "id22",
    name: "Bank",
    prev: ["id11"],
    next: ["id31", "id32"],
    pos: [2, 2],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: { gold: 1000 },
  },
  id32: {
    id: "id32",
    name: "Treasury",
    prev: ["id22", "id23"],
    next: null,
    pos: [3, 2],
    cost: { gold: 5000, gems: 5, crystals: 5, mercury: 5 },
    produces: { gold: 2000 },
  },
  id23: {
    id: "id23",
    name: "Fortifications",
    prev: null,
    next: ["id33"],
    pos: [2, 3],
    cost: { gold: 2500, ore: 5 },
    produces: {},
  },
  id33: {
    id: "id33",
    name: "Fortifications II",
    prev: ["id23"],
    next: ["id43"],
    pos: [3, 3],
    cost: { gold: 2500, ore: 10 },
    produces: {},
  },
  id43: {
    id: "id43",
    name: "Fortifications III",
    prev: ["id33"],
    next: null,
    pos: [4, 3],
    cost: { gold: 5000, ore: 15 },
    produces: {},
  },
  id04: {
    id: "id04",
    name: "Cultist Spire",
    prev: null,
    next: ["id14", "id15"],
    pos: [0, 4],
    cost: { gold: 0 },
    produces: {},
  },
  id14: {
    id: "id14",
    name: "Cultist Spire II",
    prev: ["id04"],
    next: null,
    pos: [1, 4],
    cost: { gold: 2000, wood: 5, ore: 5, dust: 20 },
    produces: {},
  },
  id24: {
    id: "id24",
    name: "House of Chains",
    prev: ["id15"],
    next: ["id34", "id35"],
    pos: [2, 4],
    cost: { gold: 4750, wood: 5, ore: 5 },
    produces: {},
  },
  id34: {
    id: "id34",
    name: "House of Chains II",
    prev: ["id24"],
    next: null,
    pos: [3, 4],
    cost: { gold: 1500, wood: 15, ore: 15, dust: 50 },
    produces: {},
  },
  id15: {
    id: "id15",
    name: "Aga'Shoth Stables",
    prev: ["id04"],
    next: ["id25", "id24", "id26"],
    pos: [1, 5],
    cost: { gold: 2750, wood: 5, ore: 5 },
    produces: {},
  },
  id25: {
    id: "id25",
    name: "Aga'Shoth Stables II",
    prev: ["id15"],
    next: null,
    pos: [2, 5],
    cost: { gold: 750, wood: 10, ore: 10, dust: 30 },
    produces: {},
  },
  id35: {
    id: "id35",
    name: "Bloated Mansion",
    prev: ["id24"],
    next: ["id45"],
    pos: [3, 5],
    cost: { gold: 7750, wood: 5, ore: 5 },
    produces: {},
  },
  id45: {
    id: "id45",
    name: "Bloated Mansion II",
    prev: ["id35"],
    next: null,
    pos: [4, 5],
    cost: { gold: 3750, wood: 20, ore: 20, dust: 75 },
    produces: {},
  },
  id06: {
    id: "id06",
    name: "Lesser Summoning Rite",
    prev: null,
    next: ["id16", "id17"],
    pos: [0, 6],
    cost: { gold: 0 },
    produces: {},
  },
  id16: {
    id: "id16",
    name: "Lesser Summoning Rite II",
    prev: ["id06"],
    next: null,
    pos: [1, 6],
    cost: { gold: 250, mercury: 5, dust: 10 },
    produces: {},
  },
  id26: {
    id: "id26",
    name: "Eerie Summoning Rite",
    prev: ["id15", "id17"],
    next: ["id36"],
    pos: [2, 6],
    cost: { gold: 12500, mercury: 20, gems: 5, crystals: 5 },
    produces: {},
  },
  id36: {
    id: "id36",
    name: "Eerie Summoning Rite II",
    prev: ["id26"],
    next: null,
    pos: [3, 6],
    cost: { gold: 17500, mercury: 25, dust: 100 },
    produces: {},
  },
  id07: {
    id: "id07",
    name: "Involuntary Summons",
    prev: null,
    next: null,
    pos: [0, 7],
    cost: { gold: 5000, mercury: 3, gems: 3, crystals: 3 },
    produces: {},
  },
  id17: {
    id: "id17",
    name: "Disturbing Summoning Rite",
    prev: ["id06", "id08"],
    next: ["id27", "id26"],
    pos: [1, 7],
    cost: { gold: 2250, mercury: 6, gems: 3, crystals: 3 },
    produces: {},
  },
  id27: {
    id: "id27",
    name: "Disturbing Summoning Rite II",
    prev: ["id17"],
    next: null,
    pos: [2, 7],
    cost: { gold: 2000, mercury: 10, dust: 40 },
    produces: {},
  },
  id08: {
    id: "id08",
    name: "Mage Guild",
    prev: null,
    next: ["id18"],
    pos: [0, 8],
    cost: { gold: 2500, wood: 5 },
    produces: {},
  },
  id18: {
    id: "id18",
    name: "Mage Guild II",
    prev: ["id08"],
    next: ["id28"],
    pos: [1, 8],
    cost: { gold: 2500, gems: 2, crystals: 2, mercury: 2 },
    produces: {},
  },
  id28: {
    id: "id28",
    name: "Mage Guild III",
    prev: ["id18"],
    next: ["id38"],
    pos: [2, 8],
    cost: { gold: 2500, wood: 5, gems: 3, crystals: 3, mercury: 3 },
    produces: {},
  },
  id38: {
    id: "id38",
    name: "Mage Guild IV",
    prev: ["id28"],
    next: null,
    pos: [3, 8],
    cost: { gold: 2500, gems: 5, crystals: 5, mercury: 5 },
    produces: {},
  },
} as const;
