export const temple = {
  id00: {
    id: "id00",
    name: "Golden Calf",
    prev: null,
    next: null,
    pos: [0, 0],
    cost: { gold: 0 },
    produces: {
      gold: 1000,
      wood: 1,
      ore: 1,
      gems: 1,
      crystals: 1,
      mercury: 1,
      dust: 1,
    },
    description:
      "The owner's cities produce 1000 Gold and 1 of each other resource daily. This city's dwellings produce +100% units.",
  },
  id10: {
    id: "id10",
    name: "Tavern",
    prev: null,
    next: ["id20"],
    pos: [1, 0],
    cost: { gold: 500, ore: 5 },
    produces: {},
    description: "Allows the hiring of new heroes.",
  },
  id20: {
    id: "id20",
    name: "Marketplace",
    prev: ["id10"],
    next: ["id31", "id30"],
    pos: [2, 0],
    cost: { gold: 500, wood: 5 },
    produces: {},
    description: "Allows resources to be traded.",
  },
  id30: {
    id: "id30",
    name: "Artifact Merchant",
    prev: ["id20"],
    next: null,
    pos: [3, 0],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: {},
    description: "Allows artifacts to be traded.",
  },
  id01: {
    id: "id01",
    name: "Solar Temple",
    prev: null,
    next: ["id11"],
    pos: [0, 1],
    cost: { gold: 0 },
    produces: { gold: 500, law: 500, astrology: 500 },
    description:
      "Grants the kingdom 500 Gold, Law points, and Astrology points daily. +1 hero cap.",
  },
  id11: {
    id: "id11",
    name: "Solar Temple II",
    prev: ["id01"],
    next: ["id21", "id22"],
    pos: [1, 1],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: { gold: 250, law: 250, astrology: 250 },
    description:
      "Grants the kingdom 750 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-1 economy upgrade.",
  },
  id21: {
    id: "id21",
    name: "Solar Temple III",
    prev: ["id11"],
    next: null,
    pos: [2, 1],
    cost: { gold: 5000, wood: 10, ore: 10 },
    produces: { gold: 250, law: 250, astrology: 250 },
    description:
      "Grants the kingdom 1000 Gold, Law points, and Astrology points daily. Allows the owner to pick one level-2 economy upgrade.",
  },
  id31: {
    id: "id31",
    name: "Resource Depot",
    prev: ["id20", "id22"],
    next: ["id41"],
    pos: [3, 1],
    cost: { gold: 2000 },
    produces: { gems: 1 },
    description: "Produces 1 Gem daily.",
  },
  id41: {
    id: "id41",
    name: "Alchemic Depot",
    prev: ["id31"],
    next: null,
    pos: [4, 1],
    cost: { gems: 3, crystals: 3, mercury: 3 },
    produces: { dust: 5 },
    description: "Produces 5 Alchemical Dust daily.",
  },
  id12: {
    id: "id12",
    name: "Guild of Six Winds",
    prev: null,
    next: null,
    pos: [1, 2],
    cost: { gold: 2500, wood: 5, ore: 5, crystals: 2, gems: 2, mercury: 2 },
    produces: {},
    description:
      "Allows a selected hero to spend a day learning. They will be unavailable until the next day and receive a permanent increase to an attribute of their choice.",
  },
  id22: {
    id: "id22",
    name: "Bank",
    prev: ["id11"],
    next: ["id31", "id32"],
    pos: [2, 2],
    cost: { gold: 2500, wood: 5, ore: 5 },
    produces: { gold: 1000 },
    description: "Produces 1000 Gold daily.",
  },
  id32: {
    id: "id32",
    name: "Treasury",
    prev: ["id22", "id23"],
    next: null,
    pos: [3, 2],
    cost: { gold: 5000, gems: 5, crystals: 5, mercury: 5 },
    produces: { gold: 2000 },
    description: "Produces 2000 Gold daily.",
  },
  id13: {
    id: "id13",
    name: "Scouting Skyship",
    prev: null,
    next: null,
    pos: [1, 3],
    cost: { gold: 2500 },
    produces: {},
    description: "Removes the fog of war within 20 squares around the city.",
  },
  id23: {
    id: "id23",
    name: "Fortifications",
    prev: null,
    next: ["id33"],
    pos: [2, 3],
    cost: { gold: 2500, ore: 5 },
    produces: {},
    description:
      "Provides walls during sieges. Allows the builder to pick one level-1 defensive upgrade.",
  },
  id33: {
    id: "id33",
    name: "Fortifications II",
    prev: ["id23"],
    next: ["id43"],
    pos: [3, 3],
    cost: { gold: 2500, ore: 10 },
    produces: {},
    description:
      "Adds two towers to the battlements that shoot at attackers during sieges. Allows the builder to pick one level-2 defensive upgrade. City dwellings produce +50% units.",
  },
  id43: {
    id: "id43",
    name: "Fortifications III",
    prev: ["id33"],
    next: null,
    pos: [4, 3],
    cost: { gold: 5000, ore: 15 },
    produces: {},
    description:
      "Adds one more grand tower to the battlements that shoots at attackers during sieges and spikes by the walls. Allows the builder to pick one level-3 defensive upgrade. City dwellings produce +100% units.",
  },
  id24: {
    id: "id24",
    name: "Garrison II",
    prev: ["id15"],
    next: null,
    pos: [2, 4],
    cost: { gold: 1000, ore: 5, dust: 10 },
    produces: {},
    description: "Allows the recruitment of Guard Captains and Sun’s Aegises.",
  },
  id34: {
    id: "id34",
    name: "Hippodrome II",
    prev: ["id25"],
    next: null,
    pos: [3, 4],
    cost: { gold: 4500, wood: 20, ore: 5, dust: 50 },
    produces: {},
    description:
      "Allows the recruitment of Noble Cavalry and Sunspear Cavalry.",
  },
  id15: {
    id: "id15",
    name: "Garrison",
    prev: null,
    next: ["id24"],
    pos: [1, 5],
    cost: { gold: 0 },
    produces: {},
    description: "Allows the recruitment of Swordsmen.",
  },
  id25: {
    id: "id25",
    name: "Hippodrome",
    prev: ["id15", "id16"],
    next: ["id34"],
    pos: [2, 5],
    cost: { gold: 6000, wood: 15 },
    produces: {},
    description: "Allows the recruitment of Cavalry.",
  },
  id35: {
    id: "id35",
    name: "Threshold Basilica",
    prev: ["id26"],
    next: ["id45"],
    pos: [3, 5],
    cost: { gold: 3500, ore: 10, gems: 10 },
    produces: {},
    description: "Allows the recruitment of Inquisitors.",
  },
  id45: {
    id: "id45",
    name: "Threshold Basilica II",
    prev: ["id35"],
    next: null,
    pos: [4, 5],
    cost: { gold: 2000, ore: 10, gems: 15, dust: 75 },
    produces: {},
    description:
      "Allows the recruitment of Mothers Superior and Excommunicators.",
  },
  id06: {
    id: "id06",
    name: "Mews",
    prev: null,
    next: ["id16", "id17"],
    pos: [0, 6],
    cost: { gold: 2250, wood: 5 },
    produces: {},
    description: "Allows the recruitment of Crossbowmen.",
  },
  id16: {
    id: "id16",
    name: "Griffin Rookery",
    prev: ["id06"],
    next: ["id26", "id27", "id25"],
    pos: [1, 6],
    cost: { gold: 3250, wood: 5, ore: 5 },
    produces: {},
    description: "Allows the recruitment of Griffins.",
  },
  id26: {
    id: "id26",
    name: "Sundrop Chapel",
    prev: ["id16"],
    next: ["id36", "id37", "id35"],
    pos: [2, 6],
    cost: { gold: 3250, gems: 3, mercury: 3, crystals: 3 },
    produces: {},
    description: "Allows the recruitment of Lightweavers.",
  },
  id36: {
    id: "id36",
    name: "Sundrop Chapel II",
    prev: ["id26"],
    next: null,
    pos: [3, 6],
    cost: { gold: 3250, gems: 6, dust: 40 },
    produces: {},
    description: "Allows the recruitment of Hierophants and Sun Heralds.",
  },
  id17: {
    id: "id17",
    name: "Mews II",
    prev: ["id06"],
    next: null,
    pos: [1, 7],
    cost: { gold: 1500, wood: 5, dust: 20 },
    produces: {},
    description: "Allows the recruitment of Austringers and Marksmen.",
  },
  id27: {
    id: "id27",
    name: "Griffin Rookery II",
    prev: ["id16"],
    next: null,
    pos: [2, 7],
    cost: { gold: 2250, wood: 5, ore: 5, dust: 30 },
    produces: {},
    description:
      "Allows the recruitment of Temple Griffins and Guardian Griffins.",
  },
  id37: {
    id: "id37",
    name: "Radiant Forge",
    prev: ["id26", "id28"],
    next: ["id47"],
    pos: [3, 7],
    cost: { gold: 15000, gems: 10, crystals: 5, mercury: 5 },
    produces: {},
    description: "Allows the recruitment of Angels.",
  },
  id47: {
    id: "id47",
    name: "Radiant Forge II",
    prev: ["id37"],
    next: null,
    pos: [4, 7],
    cost: { gold: 17500, gems: 20, dust: 100 },
    produces: {},
    description: "Allows the recruitment of Archangels and Apotheoses.",
  },
  id18: {
    id: "id18",
    name: "Mage Guild",
    prev: null,
    next: ["id28"],
    pos: [1, 8],
    cost: { gold: 2500, wood: 5 },
    produces: {},
    description:
      "Unlocks 7 random tier‑1 spells in the Magic Observatory and the ability to spend dust to upgrade tier-1 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1 spells are added to their Spellbook.",
  },
  id28: {
    id: "id28",
    name: "Mage Guild II",
    prev: ["id18"],
    next: ["id38"],
    pos: [2, 8],
    cost: { gold: 2500, gems: 2, crystals: 2, mercury: 2 },
    produces: {},
    description:
      "Unlocks 6 random tier‑2 spells in the Magic Observatory and the ability to spend dust to upgrade tier-2 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–2 spells are added to their Spellbook.",
  },
  id38: {
    id: "id38",
    name: "Mage Guild III",
    prev: ["id28"],
    next: ["id48"],
    pos: [3, 8],
    cost: { gold: 2500, wood: 5, gems: 3, crystals: 3, mercury: 3 },
    produces: {},
    description:
      "Unlocks 5 random tier‑3 spells in the Magic Observatory and the ability to spend dust to upgrade tier-3 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–3 spells are added to their Spellbook.",
  },
  id48: {
    id: "id48",
    name: "Mage Guild IV",
    prev: ["id38"],
    next: null,
    pos: [4, 8],
    cost: { gold: 2500, gems: 5, crystals: 5, mercury: 5 },
    produces: {},
    description:
      "Unlocks 4 random tier‑4 spells in the Magic Observatory and the ability to spend dust to upgrade tier-4 spells or unlock additional ones. When heroes visit the city, all unlocked tier-1–4 spells are added to their Spellbook.",
  },
} as const;
